// Versioned storage guarantees a clean start after the original demo dataset.
// All progress is created through the form and persisted locally for this browser.
const STORAGE_KEY = 'learning-progress-dashboard-v2';
const catalog = {
  DSA: ['Arrays','Strings','HashMap / HashSet','Two Pointers','Prefix Sum','Sliding Window','Stack','Monotonic Stack','Linked List','Queue','Deque','Recursion','Binary Search','Trees','BST','Heap / Priority Queue','Graphs','Greedy','Backtracking','Dynamic Programming','Other DSA Patterns'],
  Skills: ['Python','SQL','Git/GitHub','OOP','APIs','File handling','Exception handling','Libraries / Frameworks'],
  'CS Core': ['DBMS','Operating Systems','Computer Networks','OOPs','Software Engineering','Computer Architecture'],
  'AI / ML': ['Python for ML','NumPy','Pandas','Matplotlib','Statistics','Machine Learning','Deep Learning','NLP','Computer Vision','Generative AI','LLMs','AI Projects'],
  Projects: [],
  Placement: ['Aptitude','Reasoning','Verbal','Coding','Technical Interview','HR Interview','Communication','Mock Interviews']
};
let entries = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
function persist(){localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));}
function pct(v,t){return t ? Math.round(v/t*100) : 0}
function uniqueTopics(category){return [...new Set(entries.filter(e=>e.category===category).map(e=>e.topic))]}
function topicStatus(topic, category){const list=entries.filter(e=>e.topic===topic&&e.category===category); return list.some(e=>e.status==='Completed')?'Completed':list.some(e=>e.status==='Practiced')?'Practiced':list.some(e=>e.status==='Learning')?'Learning':'Not Started'}
function statusPercent(status){return { 'Not Started':0,Learning:45,Practiced:75,Completed:100}[status] || 0}
function stats(){const known=Object.values(catalog).flat();const extra=entries.filter(e=>!known.includes(e.topic)).map(e=>e.topic);const all=[...new Set([...known,...extra])];const complete=all.filter(t=>entries.some(e=>e.topic===t&&e.status==='Completed')).length;const learning=all.filter(t=>{const value=Math.max(0,...entries.filter(e=>e.topic===t).map(e=>statusPercent(e.status)));return value>0&&value<100}).length;return {all,complete,learning,overall:pct(all.reduce((sum,t)=>sum+Math.max(0,...entries.filter(e=>e.topic===t).map(e=>statusPercent(e.status))),0),all.length*100),leetcode:entries.reduce((n,e)=>n+(+e.problems||0),0),projects:entries.filter(e=>e.category==='Projects'&&e.status==='Completed').length}}
function streak(){const days=[...new Set(entries.map(e=>e.date))].sort().reverse();if(!days.length)return 0;let count=0, cursor=new Date(days[0]+'T12:00:00');for(const d of days){const current=new Date(d+'T12:00:00');if(cursor-current>86400000)break;count++;cursor.setDate(cursor.getDate()-1)}return count}
function formatDate(date){return new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(date+'T12:00:00'))}
function renderStats(){const s=stats();$$('[data-overall]').forEach(el=>el.textContent=s.overall+'%');$('[data-ring]').style.setProperty('--progress',s.overall);$('[data-completed]').textContent=s.complete;$('[data-learning]').textContent=s.learning;$('[data-total-topics]').textContent=`of ${s.all.length} tracked topics`;$('[data-projects]').textContent=s.projects;$('[data-leetcode]').textContent=s.leetcode;$('[data-streak]').textContent=streak();const days=entries.filter(e=>e.category==='DSA').length;$('[data-dsa-day]').textContent=days||'—';const focus=entries.filter(e=>e.status==='Learning').sort((a,b)=>b.date.localeCompare(a.date))[0];$('[data-focus]').textContent=focus?.topic||'Choose your next focus'}
function renderDsa(){const topics=catalog.DSA;const statuses=topics.map(t=>topicStatus(t,'DSA'));const done=statuses.filter(s=>s==='Completed').length;const progress=Math.round(statuses.reduce((n,s)=>n+statusPercent(s),0)/(topics.length*100)*100);$('[data-dsa-percent]').textContent=progress+'%';$('[data-dsa-bar]').style.width=progress+'%';$('[data-dsa-caption]').textContent=`${done} / ${topics.length} topics complete`;$(' #dsa-topics'.trim()).innerHTML=topics.map((t,i)=>({t,status:statuses[i]})).filter(x=>x.status!=='Not Started').slice(0,5).map(x=>`<div class="topic-row"><span>${x.t}</span><div class="mini-bar"><span style="width:${statusPercent(x.status)}%"></span></div><span class="badge ${x.status.replace(' ','.')}">${x.status}</span></div>`).join('')||'<p class="empty-state">Add your first DSA topic to see progress here.</p>'}
function renderSkills(){const all=['Python','SQL','Git/GitHub','OOP','DBMS','NumPy'];$('#skill-list').innerHTML=all.map(t=>{const category=['DBMS'].includes(t)?'CS Core':['NumPy'].includes(t)?'AI / ML':'Skills';const status=topicStatus(t,category);const value=statusPercent(status);return `<div class="skill-row"><span>${t}<small> · ${status}</small></span><div class="bar-track"><span style="width:${value}%"></span></div><strong>${value}%</strong></div>`}).join('')}
function renderUpcoming(){const known=Object.entries(catalog).flatMap(([c,topics])=>topics.map(t=>({c,t})));const next=known.filter(x=>topicStatus(x.t,x.c)==='Not Started').slice(0,3);$('#upcoming-list').innerHTML=next.map(x=>`<div class="upcoming"><span>${x.t}</span><small>${x.c}</small></div>`).join('')||'<p class="muted">You have started every topic in your roadmap.</p>'}
function renderChart(){const labels=[], values=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);labels.push(d.toLocaleDateString('en',{weekday:'narrow'}));values.push(entries.filter(e=>e.date===key).reduce((n,e)=>n+(+e.hours||0),0))}const max=Math.max(...values,4);$('#week-chart').innerHTML=values.map((v,i)=>`<div class="bar ${i===6?'today':''}" style="--height:${Math.max(4,v/max*100)}" title="${v} hours"></div>`).join('');$('#chart-labels').innerHTML=labels.map(d=>`<span>${d}</span>`).join('');const total=values.reduce((a,b)=>a+b,0);$('[data-week-hours]').textContent=`${total%1?total.toFixed(1):total}h`;$('[data-week-note]').textContent=total?`${total} hours logged`:'Log your first hour'}
function renderHistory(){const query=$('#search').value.trim().toLowerCase(), cat=$('#category-filter').value,status=$('#status-filter').value;const list=entries.filter(e=>!cat||e.category===cat).filter(e=>!status||e.status===status).filter(e=>!query||Object.values(e).join(' ').toLowerCase().includes(query)).sort((a,b)=>b.date.localeCompare(a.date));$('#history-list').innerHTML=list.map(e=>{const d=new Date(e.date+'T12:00:00');return `<article class="history-entry"><div class="date-block"><b>${d.getDate()}</b><span>${d.toLocaleDateString('en',{month:'short'})}</span></div><div><div class="entry-title">${escapeHtml(e.topic)} <span class="entry-meta">· ${escapeHtml(e.category)}</span></div><div class="entry-desc">${escapeHtml(e.learned)}</div></div><div class="entry-meta">${e.problems?e.problems+' problem'+(e.problems>1?'s':''):'—'} · ${e.hours}h</div><span class="badge ${e.status.replace(' ','.')}">${e.status}</span><button class="edit-btn" data-id="${e.id}">Edit</button></article>`}).join('');$('#empty-state').hidden=!!list.length;$$('.edit-btn').forEach(b=>b.addEventListener('click',()=>openForm(entries.find(e=>e.id===b.dataset.id))))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderStats();renderDsa();renderSkills();renderUpcoming();renderChart();renderHistory()}
function buildOptions(){const cats=Object.keys(catalog);$('#form-category').innerHTML=cats.map(c=>`<option>${c}</option>`).join('');$('#category-filter').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('#topic-options').innerHTML=Object.values(catalog).flat().map(t=>`<option value="${t}">`).join('')}
function openForm(entry){const form=$('#progress-form');form.reset();form.elements.date.value=new Date().toISOString().slice(0,10);$('#delete-entry').hidden=!entry;if(entry){$('#modal-kicker').textContent='EDIT ENTRY';$('#modal-title').textContent='Update learning progress';Object.entries(entry).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value})}else{$('#modal-kicker').textContent='NEW ENTRY';$('#modal-title').textContent='Add learning progress'}$('#progress-dialog').showModal()}
$('#open-add').addEventListener('click',()=>openForm());$('#quick-add').addEventListener('click',()=>openForm());$('#close-dialog').addEventListener('click',()=>$('#progress-dialog').close());$$('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>{const c=btn.dataset.preset==='Skills'?'Skills':'DSA';$('#category-filter').value=c;location.hash='history';renderHistory()}));$('#progress-form').addEventListener('submit',e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.target));const entry={...raw,problems:+raw.problems||0,hours:+raw.hours||0,id:raw.id||crypto.randomUUID()};const idx=entries.findIndex(x=>x.id===entry.id);idx>=0?entries[idx]=entry:entries.push(entry);persist();$('#progress-dialog').close();render()});$('#delete-entry').addEventListener('click',()=>{const id=$('#progress-form').elements.id.value;entries=entries.filter(e=>e.id!==id);persist();$('#progress-dialog').close();render()});$('#search').addEventListener('input',renderHistory);$('#category-filter').addEventListener('change',renderHistory);$('#status-filter').addEventListener('change',renderHistory);buildOptions();render();
